### ISSUE TITLE
Support Xcode 8 and Swift 3

### ISSUE THREAD

**Issue by leogdion** [devedup/GenerateI18NConstants#2]
I created a fork which supports Xcode 8 and Swift 3.
https://github.com/brightdigit/GenerateI18NConstants/tree/xcode8-swift3-bundle

**Comment by devedup** [comment]
Same for this as your previous issue. Why not setup a pull request and I'll merge?

**Comment by leogdion** [comment]
I don't know if you'd want this in the master branch or a separate one in order to continue to support xcode 7 and swift 2.

**Comment by 4eleven7** [comment]
Pull request so the head is as up to date as possible. Then Xcode 7 and Swift 2 support will still be available in a tag.

**Comment by leogdion** [comment]
Good to know. Pull Request #3 Added.
